### ISSUE TITLE
Opening a home channel causes Discord to crash

### ISSUE THREAD

**Issue by asportnoy** [Puyodead1/powercord-stafftags#24]
Opening the home channel in a server (eg the one in https://discord.gg/rythm) with this plugin enabled causes Discord to crash.

**Comment by Puyodead1** [comment]
It seems to be working fine on my end, are you sure its this plugin?

**Comment by asportnoy** [comment]
Yes, I was only able to replicate it with the plugin enabled. Disabling it fixed the issue. Again, this has to be a home channel, it works in regular ones.

**Comment by asportnoy** [comment]
Forgot to specify earlier but the error was https://reactjs.org/docs/error-decoder.html/?invariant=152&args%5B%5D=MessageHeader

**Comment by Puyodead1** [comment]
I tried it with the home channel in the server you mentioned

**Comment by Puyodead1** [comment]
sorry, was already working on it and didn't see this. Fixed in d97a65487e7349f57dc1e19611681e1791160c0b
