### ISSUE TITLE
Staff tag shows for bots in text channels

### ISSUE THREAD

**Issue by Waffles3438** [Puyodead1/powercord-stafftags#29]
![image](https://user-images.githubusercontent.com/96705793/186207108-2ebe05cf-bf24-491b-8823-45e5066d63ac.png)
![image](https://user-images.githubusercontent.com/96705793/186207123-7075285f-16a9-46a9-845b-6c526a24e364.png)

**Comment by asportnoy** [comment]
Can reproduce this as well

**Comment by Puyodead1** [comment]
This feature wasn't finished for chat, a PR has been merged that should add add support for respecting the setting in chat. (#28)
